### ISSUE TITLE
Request Group: Customers

### ISSUE THREAD

**Issue by AElleray** [stitch-digital/laravel-simpro-api#14]
### Feature Description

Feature Description
To include the customer create requests:

CreateCustomer (company & individual)

### API Docs
https://developer.simprogroup.com/apidoc/?page=e6d0e1c8fc6a4fcf47869df87e04cd88#operation/345fa0996f7f790e1103bebdea233fc3

### Required Requests:

- [x] GetCustomers
- [x] RetrieveCustomer
- [x] CreateCustomer
- [x] UpdateCustomer
- [x] DeleteCustomer

Attachments:

- [x] GetCustomerAttachments
- [x] RetrieveCustomerAttachment
- [x] CreateCustomerAttachment
- [x] UpdateCustomerAttachment
- [x] DeleteCustomerAttachment

Attachment Folders:

- [x] GetCustomerAttachmentFolders
- [x] RetrieveCustomerAttachmentFolder
- [x] CreateCustomerAttachmentFolder
- [x] UpdateCustomerAttachmentFolder
- [x] DeleteCustomerAttachmentFolder

Contacts:

- [x] GetCustomerContacts
- [x] RetrieveCustomerContact
- [x] CreateCustomerContact
- [x] UpdateCustomerContact
- [x] DeleteCustomerContact

Contracts:

- [x] GetCustomerContracts
- [x] RetrieveCustomerContract
- [x] CreateCustomerContract
- [x] UpdateCustomerContract
- [x] DeleteCustomerContract

Contracts -> Custom Fields:

- [x] GetCustomerContractCustomFields
- [x] RetrieveCustomerContractCustomField
- [x] UpdateCustomerContractCustomField

Contracts -> Inflation:

- [x] GetCustomerContractInflations
- [x] RetrieveCustomerContractInflation
- [x] CreateCustomerContractInflation
- [x] UpdateCustomerContractInflation
- [x] DeleteCustomerContractInflation

Contracts -> Service Levels:

- [x] GetCustomerContractServiceLevels

Contracts -> Service Levels -> Asset Types:

- [x] RetrieveCustomerContractServiceLevelAssetType
- [x] UpdateCustomerContractServiceLevelAssetType

Custom Fields:

- [x] GetCustomerCustomFields
- [x] RetrieveCustomerCustomField
- [x] UpdateCustomerCustomField

Labour Rates:

- [x] GetLaborRates
- [x] RetrieveLaborRate
- [x] CreateLaborRate
- [x] UpdateLaborRate
- [x] DeleteLaborRate

Notes:

- [x] GetCustomerNotes
- [x] RetrieveCustomerNote
- [x] CreateCustomerNote
- [x] UpdateCustomerNote
- [x] DeleteCustomerNote

Response Times:

- [x] GetCustomerResponseTimes
- [x] RetrieveCustomerResponseTime
- [x] CreateCustomerResponseTime
- [x] UpdateCustomerResponseTime
- [x] DeleteCustomerResponseTime

Tasks:

- [x] GetCustomerTasks
- [x] RetrieveCustomerTask

**Comment by johntrickett86** [comment]
@AElleray I've added all of the endpoints

**Comment by johntrickett86** [comment]
@AElleray The PHP stan tests are failing. I think it's due to an incorrect doc block on the DeleteCustomerAttachment request. If you run ./vendor/bin/phpstan it should highlight any issues.
